adminPassword: "DevOps2026Grafana"

serviceAccount:
  create: true
  autoMount: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::509399596610:role/devops-platform-dev-grafana-role

service:
  type: LoadBalancer

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: CloudWatch
        type: cloudwatch
        isDefault: true
        jsonData:
          authType: default
          assumeRoleArn: arn:aws:iam::509399596610:role/devops-platform-dev-grafana-role
          defaultRegion: us-east-1
          defaultMetricName: CPUUtilization
          period: "300"

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        folder: DevOps Platform
        type: file
        options:
          path: /var/lib/grafana/dashboards

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
